### ISSUE TITLE
How to publish `wsl-x64` architecture tarballs?

### ISSUE THREAD

**Issue by dlecan** [oclif/plugin-update#199]
Hello,

Some of our users want to upgrade their CLI, but its fails:

```
@uns/cli: Updating CLI... !
    Error: HTTP Error 404 for GET https://my.domain.com/wsl-x64
    <?xml version='1.0' encoding='UTF-8'?>
    <Error><Code>NoSuchKey</Code><Message>The specified key does not
    exist.</Message><RequestId>txb8822e97861143d598f96-005fdc9fd2</RequestId><Key>wsl-x64</Key></Error>
```
Their CLI are looking for `wsl-x64` arch packages ... which don't exist in our S3 bucket.
Of course it's linked to https://github.com/oclif/config/pull/107

How to publish them?

I want to contribute an improvement, but I don't even know if `wsl-x64` derives from Windows or Linux architecture 😜

**Comment by dlecan** [comment]
No more need that

**Comment by nanomosfet** [comment]
how did you fix this?

**Comment by dlecan** [comment]
Unfortunately with a workaround: use the Windows binaries 😥
