### ISSUE TITLE
Document the S3 file structure

### ISSUE THREAD

**Issue by mcurcio** [oclif/plugin-update#22]
Pardon me if this plugin is not ready for public consumption...

As far as I can tell, `dev pack` alone does not produce the correct directory structure to sync with S3. The Heroku CLI does some extra magic to add channel folders. What is the proper way to make the magic happen? Ideally I suppose `pack`/`publish` should incorporate channels (somehow?), but I was hoping for an expert take on the roadmap here.

**Comment by jdxcode** [comment]
The directory structure should be compatible with the update plugin out of the box. The paths are defined (and overridable in `package.json`) here: https://github.com/oclif/config/blob/master/src/config.ts#L205-L221

The update plugin will also use these same paths so you can have any structure you like.

Yes, this should be documented but I'm not sure the best place for it. I feel adding it to the release section of the docs would be adding too much detail.

**Comment by jdxcode** [comment]
Also, the Heroku CLI uses these defaults so you should be getting exactly the same thing.

**Comment by mcurcio** [comment]
Thanks for the prompt response. How would one define a channel when running `pack` and/or `publish`?

**Comment by jdxcode** [comment]
Still, I don't think this is documented anywhere. I'll see if I can add that somewhere

**Comment by jdxcode** [comment]
thoughts? https://github.com/oclif/oclif.github.io/commit/829f4ed7cdb0371d00984d34611a18ea03fdb65f

**Comment by mcurcio** [comment]
That looks great. I would suggest noting that the version change occurs in the package.json file (as opposed to, say, a command line flag).
