### ISSUE TITLE
darwin-x64 was not found on this server

### ISSUE THREAD

**Issue by mahnuh** [oclif/plugin-update#26]
When running the update command in my MacBook I only get the following error:
`<p>The requested URL /tools/proto-cli/darwin-x64 was not found on this server.</p>`

This might be the case, because oclif-dev pack only generates the files shown in this screenshot: http://sharedby.manuel-heidrich.com/dVnkqU/FfGJCl5xit

I guess darwin-x64 is missing. What am I doing wrong?

**Comment by jdxcode** [comment]
is it failing partway through? You don't have the targets manually specified in `package.json` either do you? It works fine for me on `example-multi-ts` after I set the s3 bucket.

**Comment by mahnuh** [comment]
Oh, my bad. The win build were failing because I did not have 7z installed. I assumed it would just skip and did not notice that pack failed entirely.
Maybe it would be nice if packing for a platform just skips if there is an error?

**Comment by mahnuh** [comment]
Ok, good point.
