### ISSUE TITLE
Updating CLI... not updatable

### ISSUE THREAD

**Issue by purplesquirrels** [oclif/plugin-update#49]
I am getting this message when trying to update using `my-cli update`

If I set the env variable MY_CLI_BINPATH="my-cli" then the update works.

I have installed my CLI from the tarball using npm (but not installing package from npm):
`npm i -g https://mysite.com/cli/my-cliv0.0.0.tar.gz`

According to the documentation the tarball supports update/auto-update but I keep getting the 'not updatable' message.

**Comment by purplesquirrels** [comment]
And I am aware of the other similar issue but it was closed without any helpful information.

**Comment by jdxcode** [comment]
autoupdating is only supposed to be used with non-npm installs

**Comment by purplesquirrels** [comment]
Ok thanks. Can the documentation be updated to clarify this? Currently is says 'These tarballs as well as the installers below can be made autoupdatable by adding the @oclif/plugin-update plugin.'

**Comment by jdxcode** [comment]
The docs are correct. The installers and tarballs are the only CLIs made autoupdatable

**Comment by henryhu712** [comment]
I need a usage example to get the correct configuration. I installed the plugin, but did not know how to use it exactly.

**Comment by mdonnalley** [comment]
>Sorry to revive an old thread... but does this mean that publishing via npm publish will not get the benefits of auto updating with this plugin?

That's correct
