### ISSUE TITLE
why tar extract ignore symlink

### ISSUE THREAD

**Issue by Rhain** [oclif/plugin-update#493]
https://github.com/oclif/plugin-update/blob/78311a0bdaf608d2974c59fb51dbd87e73e2b467/src/tar.ts#L14

<img width="632" alt="image" src="https://user-images.githubusercontent.com/1488036/211999309-670dac5f-8b67-4be1-8b61-ac314c27ec2a.png">

why ignore the symlink? 

Is there a way to bypass this limitation？ I need the symlink file when updated.

**Comment by mdonnalley** [comment]
@Rhain can you elaborate on what you exactly need? We're also open to a PR if you're up to the task. Thanks!

**Comment by cflee** [comment]
I just ran into this issue with lacking symlinks (and hence lacking directories) in the untarred directory by the updater, when deploying tarballs packed from an oclif project that is using pnpm's default [`nodeLinker: isolated`](https://pnpm.io/settings#nodelinker) mode.
