### ISSUE TITLE
Create a way to pass a post update command

### ISSUE THREAD

**Issue by Aghassi** [oclif/plugin-update#51]
I noticed that this update command doesn’t have any lifecycle hooks. Currently, the CLI we are building wraps Cypress for functionality. When we run `update` on our CLI, it won’t download the latest version of Cypress (this is usually done on post install via NPM/Yarn). Is there a way we can add a post update lifecycle to call things in particular? For example, on a successful update, I want to force the system to download the latest version of Cypress via a command Cypress provides.

**Comment by jdxcode** [comment]
it [has a hook](https://github.com/oclif/plugin-update/blob/master/src/commands/update.ts#L41)

**Comment by Aghassi** [comment]
Ah ok, I didn’t notice that. So is the recommended way to create a hook in my CLI called `update` and I have it do whatever I need in there?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
