### ISSUE TITLE
Updates are not cleaned up

### ISSUE THREAD

**Issue by pimterry** [oclif/plugin-update#56]
When updating an Oclif CLI, it seems like the old versions and other partially updated versions are not cleaned up. For clis that are frequently updated, that means they take up progressively more and more space with each release, and generally feels a bit messy & wasteful.

Is this expected behaviour? Is there an option somewhere to handle cleanup, or are there any plans to add one in future?

**Comment by mshanemc** [comment]
That's been handled, but we never updated the issue.  Sorry!
https://github.com/oclif/plugin-update/blob/8e54520cef45a4f1c56e0a2ec04af32a6b0021c8/src/update.ts#L355
